name: Integration Tests

on: pull_request

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Setup Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.14'

    - name: Install Dependencies
      run: |
        pip install -r requirements-dev.txt
        pip install .

    - name: Install PARAM
      run: |
        git clone https://github.com/facebookresearch/param.git
        cd param/train/compute/python/
        git checkout c83ce8429110a86549c40fec5a01acbd9fbd54a4
        pip install .

    - name: Extract and Validate
      run: |
        python3 ci_tools/integration_tests.py --tgz_path tests/data/1.0.2-chakra.0.0.4/llama_pytorch24.05.tgz \
                                     --num_ranks 8 --tolerance 0.05 --expected_times_ms 14597 14597 14968 14638 14649 14700 14677 14735
