name: Python Unit Tests

on: pull_request

jobs:
  python-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.14'

    - name: Install Chakra
      run: |
        pip install .

    - name: Install PARAM
      run: |
        git clone https://github.com/facebookresearch/param.git
        cd param/et_replay
        git checkout 884a1f0154a16e2c170e456f8027f2646c9108ae
        sed -i '/param_bench/d' pyproject.toml
        pip install .

    - name: Install Dependencies
      run: |
        pip install -r requirements-dev.txt

    - name: Run Unit Tests
      run: |
        python -m pytest -vv tests
